- name: kubeadm reset
  command: kubeadm reset

#- name: Reset data in etcd
#  command: etcdctl rm --recursive registry
#  when: mode == "master"

- name: Remove /var/lib/cni
  file: path=/var/lib/cni state=absent

- name: Remove /run/flannel
  file: path=run/flannel state=absent

- name: Remove /etc/cni
  file: path=/etc/cni state=absent

- name: Bring down cni0
  command: ifconfig cni0 down
  ignore_errors: true

- name: Delete cni0
  command: brctl delbr cni0
  ignore_errors: true

#- name: Update APT package cache and upgrade
#  apt:
#    update_cache: yes
#    upgrade: safe
#    state: latest

- name: Reboot
  shell: sleep 2 && reboot
  async: 1
  poll: 0
  ignore_errors: true

- name: Waiting for servers
  local_action: wait_for host={{ inventory_hostname }} state=started delay=10 timeout=60
