
- name: Install Kubernetes
  include: ../../includes/install_binaries.yml
  vars:
    binaries:
      name: kubernetes
      version: "{{ version.kubernetes }}"
      commands:
        - kubelet
        - kubectl

- name: Create Kubernetes config directory
  file: path=/etc/kubernetes/manifests/ state=directory recurse=no owner=root group=root mode=0755

- name: Copy configuration
  template: src=kubernetes-{{ mode }}.yml dest=/etc/kubernetes/manifests/kubernetes.yaml

- name: Setup profile
  template: src=kubernetes_profile.sh dest=/etc/profile.d/kubernetes.sh mode=0644

- name: Install kubelet service definition
  template: src=kubelet.service dest=/lib/systemd/system/kubelet.service owner=root group=root mode=0644

- name: Enable and start kubelet service
  service: name=kubelet enabled=true state=started
