- name: kubeadm-master | Copy init file for kubeadm
  template: src=kubeadm.yml dest=/etc/kubernetes/kubeadm.yml mode=0755

- name: kubeadm-master | Clean up /var/lib/kubelet/ 
  file: path=/var/lib/kubelet/pki state=absent
    
- name: kubeadm-master | Run kubeadm init on master
  command: kubeadm init --config /etc/kubernetes/kubeadm.yml
  register: kubeadm_init

- name: kubeadm-master | Create a dedicated token from master
  command: kubeadm token create --ttl 0 --groups system:bootstrappers:kubeadm:default-node-token --description "Bootstrap token which does not expire"
  register: kubeadm_gen_token

- name: kubeadm-master | Copy token to local file 'kubernetes-token'
  become: no
  copy: content={{ kubeadm_gen_token.stdout }} dest={{ playbook_dir }}/run/kubeadm-token.txt
  delegate_to: localhost

- name: kubeadm-master | Register token as fact
  set_fact:
    kubeadm_token: "{{ lookup('file', playbook_dir + '/run/kubeadm-token.txt') }}"

- name: kubeadm-master | Copy Kubernetes access config to ~/.kube/config on nodes
  copy: remote_src=True src=/etc/kubernetes/admin.conf dest=/home/pi/.kube/config owner=pi group=pi

# - debug: var=kubeadm_init.stdout

- name: kubeadm-master | Download cluster configuration
  fetch:
    src: "/etc/kubernetes/admin.conf"
    dest: "{{ playbook_dir }}/run/"
    flat: true

- name: kubeadm-master | Rename cluster configuration
  become: no
  command: mv {{ playbook_dir }}/run/admin.conf {{ playbook_dir }}/run/pi-cluster.cfg
  delegate_to: localhost

- name: kubeadm-master | Install CNI plugin for {{ overlay_network }}
  include: cni/{{ overlay_network }}.yml

- name: kubeadm-master | Download cluster configuration
  fetch:
    src: "/etc/kubernetes/admin.conf"
    dest: "{{ playbook_dir }}/run/"
    flat: true
  
