- name: Copy init file for kubeadm
  template: src=kubeadm.yml dest=/etc/kubernetes/kubeadm.yml mode=0755

- name: Run kubeadm init on master
#  environment:
    # Temporary until 1.6 is released
#    KUBE_HYPERKUBE_IMAGE: luxas/hyperkube:v1.6.0-and-PR-42911
  command: kubeadm init --config /etc/kubernetes/kubeadm.yml
  register: kubeadm_init

- name: Copy Kubernetes access config to ~/.kube/config on nodes
  copy: remote_src=True src=/etc/kubernetes/admin.conf dest=/home/pi/.kube/config owner=pi

# - debug: var=kubeadm_init.stdout

- name: Download cluster configuration
  fetch:
    src: "/etc/kubernetes/admin.conf"
    dest: "{{ playbook_dir }}/run/"
    flat: true

- name: Rename cluster configuration
  local_action: command mv {{ playbook_dir }}/run/admin.conf {{ playbook_dir }}/run/pi-cluster.cfg

- name: Install CNI plugin for {{ overlay_network }}
  include: cni/{{ overlay_network }}.yml
