- name: Install flanneld
  include: ../../includes/install_binaries.yml
  vars:
    binaries:
      name: flannel
      version: "{{ version.flannel }}"
      commands:
        - flanneld

- name: Extract master IP into variable master_ip
  command: sh -c "grep master /etc/hosts | awk '{print $1}'"
  register: master_from_hosts

- set_fact: master_ip={{ master_from_hosts.stdout }}

- name: Create flannel env directory
  file: path=/var/lib/flannel state=directory recurse=false

- name: Ensure that target directory /etc/kubernetes exists
  file: path=/etc/kubernetes state=directory recurse=false

- name: Add flannel_init.sh for setting flannel network
  template: src={{ mode }}/flannel_init.sh dest=/etc/kubernetes/flannel_init.sh mode=0755

- name: Install flannel service definition
  template: src={{ mode }}/flannel.service dest=/lib/systemd/system/flannel.service owner=root group=root mode=0644

- name: Enable and start flannel service
  service: name=flannel enabled=true state=started
