reset: false
overlay_network: flannel
network:
  service_subnet: 10.200.100.0/24
  pod_subnet: 10.1.0.0/16
images:
  flannel: quay.io/coreos/flannel:v0.9.0-arm
  weave: weaveworks/weave-kube:2.0.4
  weave_npc: weaveworks/weave-npc:2.0.4
k8s:
  version: 1.8.0*
  # Timing is good for demos. Defaults are 5min eviction and 40s node grace period
  # TODO: Not yet put into the k8s configuration
  pod_eviction_timeout: 5s
  node_monitor_grace_period: 10s
docker:
  # devicemapper or overlay2
  storage_driver: devicemapper
  expose_tcp: true
  version: "17.03*"
debug_level: 2
