apiVersion: v1
kind: Pod
metadata:
  name: kube-master
  namespace: kube-system
spec:
  hostNetwork: true
  volumes:
  - name: "certs-volume"
    hostPath:
      path: "/etc/kubernetes/certs"
  containers:
    - name: "kube-apiserver"
      image: "{{ images.hyperkube }}"
      args:
        - "/hyperkube"
        - "apiserver"
        - "--allow-privileged=true"
        - "--etcd-servers=http://master:{{ etcd.port }}"
        - "--insecure-bind-address=0.0.0.0"
        - "--service-cluster-ip-range={{ network.service_subnet }}"
        - "--service-node-port-range=30000-37000"
        - "--v={{ debug_level }}"
    - name: "kube-controller-manager"
      image: "{{ images.hyperkube }}"
      volumeMounts:
      - name: "certs-volume"
        mountPath: "/etc/kubernetes/certs"
      args:
        - "/hyperkube"
        - "controller-manager"
        - "--master=http://127.0.0.1:8080"
        - "--root-ca-file=/etc/kubernetes/certs/ca.crt"
        - "--service-account-private-key-file=/etc/kubernetes/certs/server.key"
        - "--pod-eviction-timeout={{ k8s.pod_eviction_timeout }}"
        - "--node-monitor-grace-period={{ k8s.node_monitor_grace_period }}"
        - "--v={{ debug_level }}"
    - name: "kube-scheduler"
      image: "{{ images.hyperkube }}"
      args:
        - "/hyperkube"
        - "scheduler"
        - "--master=http://127.0.0.1:8080"
        - "--v={{ debug_level }}"
    - name: "kube-proxy"
      image: "{{ images.hyperkube }}"
      args:
        - "/hyperkube"
        - "proxy"
        - "--master=http://127.0.0.1:8080"
        - "--v={{ debug_level }}"
      securityContext:
        privileged: true
