---
- name: Add and update packages
  include: apt.yml

- name: Add Swapfile
  include: swap.yml
  vars:
    swap_file_path: "/swapfile"
    swap_file_size: "1G"

- name: Setup system parameters (boot, hosts, timzone)
  include: system.yml

- name: Configure Wifi
  include: wifi.yaml
  when: wifi is defined

- name: Setup user
  include: user.yml
