- name: Add cgroup for Memory limits to bootparams
  lineinfile:
    dest: /boot/cmdline.txt
    regexp: '^(.*?)(\s*cgroup_enable.*swapaccount=\d+)?$'
    line: '\1 cgroup_enable=memory swapaccount=1'
    backrefs: true
    state: present

- name: Add overlay filesystem module
  lineinfile: dest=/etc/modules state=present line="overlay" insertafter="EOF"

- name: Load overlay module
  modprobe: name=overlay state=present

- name: Setup profile
  copy: src=docker_profile.sh dest=/etc/profile.d/docker.sh mode=0644

- name: Set timezone variables
  copy:
    content: "{{ timezone }}"
    dest: /etc/timezone
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata

- name: Add hosts
  template: src=hosts dest=/etc/hosts

- name: Set hostname
  hostname: name="{{ name }}"

- name: Restart hostname
  shell: "hostnamectl set-hostname {{ name }}"
