- name: Setup profile
  copy: src=docker_profile.sh dest=/etc/profile.d/docker.sh mode=0644

- name: Set timezone
  timezone: name="{{ timezone }}"

- name: Update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata

- name: Add hosts
  template: src=hosts dest=/etc/hosts

- name: Check DHCP hooks
  stat: path=/etc/dhcp/dhclient-enter-hooks.d
  register: dhclient_hooks
- name: Copy hosts to DHCP setup
  template: src=hosts dest=/etc/dhcp
  when: dhclient_hooks.stat.exists
- name: Add DHCP hook to copy etc hosts
  copy: src=copy_hosts dest=/etc/dhcp/dhclient-enter-hooks.d/ mode=0755

- name: Set hostname
  hostname: name="{{ name }}"

  # Needed only for hypriot
- stat: path=/boot/device-init.yaml
  register: device_init_file
- name: Set hostname in boot configuration
  lineinfile:
    dest: /boot/device-init.yaml
    regexp: '^(.*hostname:)\s*(.*?)\s*$'
    line: '\1 {{ name }}'
    backrefs: true
    state: present
  when: device_init_file.stat.exists

- name: Add useDns=no to /etc/ssh/sshd_config
  lineinfile: dest=/etc/ssh/sshd_config state=present line="UseDNS no" insertafter="EOF"

- name: Restart hostname
  shell: "hostnamectl set-hostname {{ name }}"
